CREATE DATABASE DB_CURSODAMINHAVIDA;

USE DB_CURSODAMINHAVIDA;
CREATE TABLE TB_CATEGORIA(
ID_CATEGORIA_ INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_CATEGORIA VARCHAR(255)
);

CREATE TABLE TB_CURSO(
ID_CURSO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_CURSO VARCHAR(255),
VALOR_CURSO DOUBLE(255,2),
VAGAS_CURSO INT,
ID_CATEGORIA int,
CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA_)
);

INSERT INTO TB_CATEGORIA(NOME_CATEGORIA)
VALUES ("ENGENHARIA"), ("ADMINISTRAÇÃO"), ("INFORMATICA"), ("QUIMICA");

INSERT INTO TB_CURSO (NOME_CURSO, VALOR_CURSO, VAGAS_CURSO, ID_CATEGORIA)VALUES
("JAVA FULL STACK",25.00,30,1), 
("GAME DEVELOPMENT",25.00,20,1),
("GESTÃO EMPRESARIAL",35.28,20,2),
("ENGENHARIA DE PRODUÇÃO",25.00,80,3),
("ENGENHARIA DA SEGURANÇA DO TRABALHO",37.00,80,3),
("GESTÃO DE RH",65.99,40,2),
("LOGISTICA",45.33,50,2),
("COSMETOLOGIA",15.00,30,4);

SELECT * FROM TB_CURSO WHERE VALOR_CURSO > 50;
SELECT * FROM TB_CURSO WHERE VALOR_CURSO BETWEEN 3 AND 60;
SELECT * FROM TB_CURSO WHERE NOME_CURSO LIKE "J%";
SELECT * FROM TB_CURSO TB_CURSO INNER JOIN TB_CATEGORIA ON TB_CURSO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA_;

SELECT * FROM TB_CURSO
INNER JOIN TB_CATEGORIA ON TB_CURSO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA_
WHERE ID_CATEGORIA = 1;

