CREATE DATABASE DB_FARMACIA_DO_BEM;

USE DB_FARMACIA_DO_BEM;

CREATE TABLE TB_CATEGORIA(
ID bigint AUTO_INCREMENT,
CATEGORIA VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO TB_CATEGORIA (CATEGORIA)
VALUES ("ANTIBIÓTICO");

INSERT INTO TB_CATEGORIA (CATEGORIA)
VALUES ("ANTIVIRAL");

INSERT INTO TB_CATEGORIA (CATEGORIA)
VALUES ("ANTI-INFLAMATÓRIO");

INSERT INTO TB_CATEGORIA (CATEGORIA)
VALUES ("ANALGÉSICO");

INSERT INTO TB_CATEGORIA (CATEGORIA)
VALUES ("CORTICOIDE");

SELECT * FROM TB_CATEGORIA;

CREATE TABLE TB_PRODUTO(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
DOSAGEM DECIMAL(6,2),
APRESENTACAO VARCHAR (255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);
INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("PREDNISONA", 20.00, "COMPRIMIDOS", 3);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("NIMESULMIDA", 100.00, "COMPRIMIDOS", 2);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("IBUUPROFENO", 400.00, "COMPRIMIDOS", 5);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("AMOXICILINA", 500.00, "CÁPSULAS", 1);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("CETOPROFENO", 100.00, "COMPRIMIDOS", 2);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("DEXAMETASONA", 5.0, "LIQUIDO", 3);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("DIPIRONA", 500.00, "COMPRIMIDOS", 5);

INSERT INTO TB_PRODUTO(NOME, DOSAGEM, APRESENTACAO, CATEGORIA_ID)
VALUES("ANCICLOVIR", 200.00, "COMPRIMIDOS", 4);

ALTER TABLE TB_PRODUTO ADD VALOR DECIMAL(8,2);

UPDATE TB_PRODUTO SET VALOR = 19.90 WHERE ID = 1;
UPDATE TB_PRODUTO SET VALOR = 30.50 WHERE ID = 2;
UPDATE TB_PRODUTO SET VALOR = 45.70 WHERE ID = 3;
UPDATE TB_PRODUTO SET VALOR = 59.90 WHERE ID = 4;
UPDATE TB_PRODUTO SET VALOR = 42.60 WHERE ID = 5;
UPDATE TB_PRODUTO SET VALOR = 25.45 WHERE ID = 6;
UPDATE TB_PRODUTO SET VALOR = 15.90 WHERE ID = 7;
UPDATE TB_PRODUTO SET VALOR = 36.40 WHERE ID = 8;

SELECT * FROM TB_PRODUTO;

SELECT * FROM TB_PRODUTO WHERE VALOR > 50.00;

SELECT * FROM TB_PRODUTO WHERE VALOR BETWEEN 3.00 AND 60.00;

SELECT * FROM TB_PRODUTO WHERE NOME LIKE "%B%";

SELECT NOME, DOSAGEM, APRESENTACAO, VALOR, TB_CATEGORIA.CATEGORIA FROM TB_PRODUTO INNER JOIN TB_CATEGORIA ON TB_PRODUTO.CATEGORIA_ID = TB_CATEGORIA.ID;

SELECT NOME, DOSAGEM, APRESENTACAO, VALOR, TB_CATEGORIA.CATEGORIA FROM TB_PRODUTO INNER JOIN TB_CATEGORIA ON TB_PRODUTO.CATEGORIA_ID = TB_CATEGORIA.ID WHERE TB_CATEGORIA.CATEGORIA = "ANALGESICO";

