CREATE DATABASE APP_COMERCIO;

USE APP_COMERCIO;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
JOGOS VARCHAR(255) NOT NULL,
VIDEOGAME VARCHAR(255) NOT NULL,
QUANTIDADE INT,
VALOR DECIMAL (6,2) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("FAR CRY5", XBOX , 25, 250.99);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("FORZA HORIZON 5", XBOX , 20, 299.99);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("RESIDENT EVIL VILLAGE", XBOX , 5, 199.99);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("ASSASSIN'S CREED VALHALLA", XBOX , 30, 399.99);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("FIFA 22", XBOX , 15, 200.99);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("CALL OF DUTY VANGUARD", XBOX , 40, 499.99);

INSERT INTO TB_PRODUTOS (JOGO, VIDEOGAME, QUANTIDADE, VALOR)
VALUES ("BATTLEFIELD 2042", XBOX , 50, 399.99);

SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_PRODUTOS WHERE VALOR > 500;
SELECT * FROM TB_PRODUTOS WHERE VALOR < 500;

UPDATE TB_PRODUTOS SET VALOR = 190.90 WHERE ID = 5;



