CREATE DATABASE REGISTRO_ESCOLA;

USE REGISTRO_ESCOLA;

CREATE TABLE TB_ESTUDANTES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
IDADE INT,
DATA_NASCIMENTO DATE,
TURMA VARCHAR(255) NOT NULL,
NOTA_FINAL DECIMAL (3,1) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("RODRIGO NERIS COSTA",21,"2000-08-09","TURMA56",9.0);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("LUCAS FERREIRA SILVA",23,"1998-04-30","TURMA56",9.7);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("DENIS CARVALHO",22,"1999-05-28","TURMA56",8.5);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("VINICIUS VIEIRA",20,"2002-02-15","TURMA56",3.0);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("TALITA BENTO",22,"2002-12-08","TURMA56",8.0);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("LARISSA",19,"2000-01-23","TURMA56",9.7);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("JENNIFER",21,"2000-05-12","TURMA56",5.5);

INSERT INTO TB_ESTUDANTES (NOME, IDADE, DATA_NASCIMENTO, TURMA, NOTA_FINAL) VALUES
("SARA BEATRIZ",20,"2002-09-25","TURMA56",6.0);

SELECT * FROM TB_ESTUDANTES;
SELECT * FROM TB_ESTUDANTES WHERE NOTA_FINAL < 7.0;
SELECT * FROM TB_ESTUDANTES WHERE NOTA_FINAL > 7.0;

UPDATE TB_ESTUDANTES SET NOTA_FINAL = 8.3 WHERE ID =2;
